### ISSUE TITLE
Add support for stylelint 11.0.0

### ISSUE THREAD

**Issue by EvgenyOrekhov** [Moxio/stylelint-selector-tag-no-without-class#3]
The plugin gives warnings that it needs stylelint >= 9.x < 11

https://github.com/Moxio/stylelint-selector-tag-no-without-class/blob/afb2955e8567517ed33f617a4071d282cdde2f5d/package.json#L32

**Comment by aboks** [comment]
I've relaxed the `peerDependencies` and released version 2.0.2 to be compatible with Stylelint 11. Thanks for raising this issue.
